import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import {LoginBtn, LogoutBtn} from './login'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let check = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar"> 
      
      <Link href="/" className="logo">Appleforum</Link> 
      <Link href="/write">Write</Link> 
      <Link href="/list">List</Link> 
      {
        check ? <span>{check.user.name} <LogoutBtn></LogoutBtn></span> : <LoginBtn></LoginBtn>  
      }
      </div>  {children}</body>
    </html>
  )
}
